# Ce circuit téléchargera une version préconstruite de Ruby, installera les dépendances et exécutera les tests avec Rake.
# Pour plus d'informations, voir : https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ 'master' ]

  # Permet d'exécuter ce circuit manuellement à partir de l'onglet Actions
  workflow_dispatch:

# Définit les permissions du GITHUB_TOKEN pour permettre le déploiement vers les pages GitHub.
permissions:
  contents: read
  pages: write
  id-token: write

# N'autoriser qu'un seul déploiement simultané, en ignorant les exécutions en file d'attente entre l'exécution en cours et la dernière en file d'attente.
# Cependant, il ne faut PAS annuler les exécutions en cours car il faut permettre à ces déploiements de production de s'achever.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Tâche de construction
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']
    steps:
      - name: Changement de branche
        uses: actions/checkout@v4
      - name: Mise en place de Ruby
      # Pour obtenir automatiquement les corrections de bogues et les nouvelles versions de Ruby pour ruby/setup-ruby,
      # modifier en (voir https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # exécute 'bundle install' et met automatiquement en cache les gemmes installées
      - name: Mise en place de Github Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Construction du site web
        # Sortie dans le répertoire './_site'.
        run: |
          bundle exec ruby scripts/générer_site.rb
          mkdir --parents ./_site
          cp --recursive --no-target-directory ./site ./_site
      - name: Téléversement des artefacts
        # Chargement automatique des artefacts à partir du répertoire './_site' par défaut
        uses: actions/upload-pages-artifact@v1
  # Tâche de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déploiement vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
